version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "start:legacy"]
  test:
    build: ./backend
    environment:
      NODE_ENV: test
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["sh", "-c", "npm run pretest && npm run test"]


